version: '3'
services:
  web:
    build: 
      context: .
    ports: 
      - "80:3000"
      - "9229:9229"
    env_file:
      - .env
    command: sh custom/compose_run
    volumes:
      - .:/usr/src/app/custom
  redis:
    image: "redis:alpine"